build_script:
  - ScaleFinderUI\ScaleFinderUI.sln
  
build:
  verbosity: normal
  
configuration: Release

deploy:
  release: ScaleFinderUI-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: cxiHYFfint9KkR184q7kzHfxk4WEvRo6QG6IGZ+emXCOviMV/3mOQJqmDxKjIh4e
  draft: false
  prerelease: false
  on:
    branch: master
artifacts: 
  - path: ScaleFinderUI.exe
test:
  assemblies:
    - ScaleFinderUI\ScaleFinderLogicTest\bin\Release\ScaleFinderLogicTest.dll